Ejercicio de Curriculo hecho
2DAW-CarlosIII/marcapersonalfp24_25 pull request #52
Opened 2024-11-21 08:15 UTC by Adrimrtz16

2024-11-21 08:32 UTC, Dspatrick29 approved these changes

2024-11-21 08:34 UTC, Dspatrick29 requested changes
El test falta

2024-11-21 08:36 UTC, AlejandroPedreno requested changes
Falta el test currículo

2024-11-21 08:47 UTC, DavidMartinezDAW approved these changes

2024-11-21 08:57 UTC, DavidMartinezDAW reviewed
Falta el test currículo

2024-11-21 08:57 UTC, DavidMartinezDAW requested changes
Falta el test currículo

2024-11-21 09:17 UTC, Adrimrtz16 commented
Ya está todo arreglado

2024-11-21 09:24 UTC, Dspatrick29 approved these changes
Todo funciona correctamente y el test esta correcto

2024-11-21 09:51 UTC, Alejandro83658 approved these changes
Todo correcto!!!

2024-11-21 11:15 UTC, AlejandroPedreno approved these changes
Ahora está correcto

2024-11-21 11:18 UTC, DavidMartinezDAW approved these changes
Todo perfecto ahora

2024-11-24 16:46 UTC, merged

2024-11-24 16:46 UTC, albsierra commented
closes #25